apiVersion: apps/v1
kind: Deployment
metadata:
  name: meu-deploy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: meu-deploy
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 300
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: meu-deploy
    spec:
      containers:
        - name: meu-deploy
          env:
          - name: DB_HOST
            value: database
          image: k1cornelsenp/projeto-ecommerce
          ports:  
            - containerPort: 80
              name: http
