apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
spec:
  serviceName: "database-service"
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database  # Certifique-se de que este label corresponde ao seletor do Serviço
    spec:
      containers:
        - name: database
          image: k1cornelsenp/projeto-ecommerce-db:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "senhasecure123#"
            - name: MYSQL_DATABASE
              value: "projetosemestral"
            - name: MYSQL_USER
              value: "toor"
            - name: MYSQL_PASSWORD
              value: "senhasecure1234#"
          volumeMounts:
            - name: database-storage
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: database-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi

