apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
spec:
  serviceName: "database-service"
  replicas: 1  # Maintain only 1 replica
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: k1cornelsenp/projeto-ecommerce-db:latest  # Custom MySQL image
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "senhasecure123#"
        - name: MYSQL_DATABASE
          value: "projetosemestral"
        - name: MYSQL_USER
          value: "toor"
        - name: MYSQL_PASSWORD
          value: "senhasecure1234#"
        volumeMounts:
        - name: database-storage
          mountPath: /var/lib/mysql
        # Optionally, add a ConfigMap volume to run initialization scripts
        - name: mysql-init
          mountPath: /docker-entrypoint-initdb.d  # MySQL will run scripts here
          readOnly: true
  volumeClaimTemplates:
  - metadata:
      name: database-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi  # Reduced size for storage
